// <auto-generated />
using System;
using BGC_DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BGCDataAccess.Migrations
{
    [DbContext(typeof(BGCContext))]
    [Migration("20221225171726_RemovedPasswordAndRoleFromMember")]
    partial class RemovedPasswordAndRoleFromMember
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BGC_DataAccess.Entities.Game", b =>
                {
                    b.Property<int>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GameId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MaxNumberPlayers")
                        .HasColumnType("int");

                    b.Property<int?>("MinNumberPlayers")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GameId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("BGC_DataAccess.Entities.GameSession", b =>
                {
                    b.Property<int>("GameSessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GameSessionId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GameTableId")
                        .HasColumnType("int");

                    b.Property<int?>("Length")
                        .HasColumnType("int");

                    b.Property<int?>("MaxNumberPlayers")
                        .HasColumnType("int");

                    b.Property<int?>("MinNumberPlayers")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OrganizerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Schedule")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("GameSessionId");

                    b.HasIndex("GameTableId");

                    b.HasIndex("OrganizerId");

                    b.ToTable("GameSessions");
                });

            modelBuilder.Entity("BGC_DataAccess.Entities.GameSessionGame", b =>
                {
                    b.Property<int>("GameSessionGameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GameSessionGameId"));

                    b.Property<int>("GameSessionId")
                        .HasColumnType("int");

                    b.Property<int>("GameVersionId")
                        .HasColumnType("int");

                    b.HasKey("GameSessionGameId");

                    b.HasIndex("GameSessionId");

                    b.HasIndex("GameVersionId");

                    b.ToTable("GameSessionGames");
                });

            modelBuilder.Entity("BGC_DataAccess.Entities.GameSessionRegistration", b =>
                {
                    b.Property<int>("GameSessionRegistrationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GameSessionRegistrationId"));

                    b.Property<int>("GameSessionId")
                        .HasColumnType("int");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.HasKey("GameSessionRegistrationId");

                    b.HasIndex("GameSessionId");

                    b.HasIndex("MemberId");

                    b.ToTable("GameSessionRegistrations");
                });

            modelBuilder.Entity("BGC_DataAccess.Entities.GameTable", b =>
                {
                    b.Property<int>("GameTableId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GameTableId"));

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.HasKey("GameTableId");

                    b.ToTable("GameTables");
                });

            modelBuilder.Entity("BGC_DataAccess.Entities.GameVersion", b =>
                {
                    b.Property<int>("GameVersionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GameVersionId"));

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.HasKey("GameVersionId");

                    b.HasIndex("GameId");

                    b.ToTable("GameVersions");
                });

            modelBuilder.Entity("BGC_DataAccess.Entities.Member", b =>
                {
                    b.Property<int>("MemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MemberId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MemberId");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("BGC_DataAccess.Entities.RpgCampaign", b =>
                {
                    b.Property<int>("RpgCampaignId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RpgCampaignId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OrganizerId")
                        .HasColumnType("int");

                    b.HasKey("RpgCampaignId");

                    b.HasIndex("OrganizerId");

                    b.ToTable("RpgCampaigns");
                });

            modelBuilder.Entity("BGC_DataAccess.Entities.RpgCampaignRegistration", b =>
                {
                    b.Property<int>("RpgCampaignRegistrationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RpgCampaignRegistrationId"));

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<int>("RpgCampaignId")
                        .HasColumnType("int");

                    b.HasKey("RpgCampaignRegistrationId");

                    b.HasIndex("MemberId");

                    b.HasIndex("RpgCampaignId");

                    b.ToTable("RpgCampaignRegistrations");
                });

            modelBuilder.Entity("BGC_DataAccess.Entities.RpgSession", b =>
                {
                    b.Property<int>("RpgSessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RpgSessionId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GameTableId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RpgCampaignId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Schedule")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("RpgSessionId");

                    b.HasIndex("GameTableId");

                    b.HasIndex("RpgCampaignId");

                    b.ToTable("RpgSessions");
                });

            modelBuilder.Entity("BGC_DataAccess.Entities.RpgSessionGame", b =>
                {
                    b.Property<int>("RpgSessionGameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RpgSessionGameId"));

                    b.Property<int>("GameVersionId")
                        .HasColumnType("int");

                    b.Property<int>("RpgSessionId")
                        .HasColumnType("int");

                    b.HasKey("RpgSessionGameId");

                    b.HasIndex("GameVersionId");

                    b.HasIndex("RpgSessionId");

                    b.ToTable("RpgSessionGames");
                });

            modelBuilder.Entity("BGC_DataAccess.Entities.GameSession", b =>
                {
                    b.HasOne("BGC_DataAccess.Entities.GameTable", "GameTable")
                        .WithMany("GameSessions")
                        .HasForeignKey("GameTableId");

                    b.HasOne("BGC_DataAccess.Entities.Member", "Organizer")
                        .WithMany("GameSessions")
                        .HasForeignKey("OrganizerId");

                    b.Navigation("GameTable");

                    b.Navigation("Organizer");
                });

            modelBuilder.Entity("BGC_DataAccess.Entities.GameSessionGame", b =>
                {
                    b.HasOne("BGC_DataAccess.Entities.GameSession", "GameSession")
                        .WithMany("GamesSessionGames")
                        .HasForeignKey("GameSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BGC_DataAccess.Entities.GameVersion", "GameVersion")
                        .WithMany("GameSessionGames")
                        .HasForeignKey("GameVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameSession");

                    b.Navigation("GameVersion");
                });

            modelBuilder.Entity("BGC_DataAccess.Entities.GameSessionRegistration", b =>
                {
                    b.HasOne("BGC_DataAccess.Entities.GameSession", "GameSession")
                        .WithMany("GameSessionRegistrations")
                        .HasForeignKey("GameSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BGC_DataAccess.Entities.Member", "Player")
                        .WithMany("GameSessionRegistrations")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameSession");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("BGC_DataAccess.Entities.GameVersion", b =>
                {
                    b.HasOne("BGC_DataAccess.Entities.Game", "Game")
                        .WithMany("Versions")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("BGC_DataAccess.Entities.RpgCampaign", b =>
                {
                    b.HasOne("BGC_DataAccess.Entities.Member", "Organizer")
                        .WithMany("RpgCampaigns")
                        .HasForeignKey("OrganizerId");

                    b.Navigation("Organizer");
                });

            modelBuilder.Entity("BGC_DataAccess.Entities.RpgCampaignRegistration", b =>
                {
                    b.HasOne("BGC_DataAccess.Entities.Member", "Player")
                        .WithMany("RpgCampaignRegistrations")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BGC_DataAccess.Entities.RpgCampaign", "RpgCampaign")
                        .WithMany("RpgCampaignRegistrations")
                        .HasForeignKey("RpgCampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("RpgCampaign");
                });

            modelBuilder.Entity("BGC_DataAccess.Entities.RpgSession", b =>
                {
                    b.HasOne("BGC_DataAccess.Entities.GameTable", "Table")
                        .WithMany("RpgSessions")
                        .HasForeignKey("GameTableId");

                    b.HasOne("BGC_DataAccess.Entities.RpgCampaign", "Campaign")
                        .WithMany("Sessions")
                        .HasForeignKey("RpgCampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");

                    b.Navigation("Table");
                });

            modelBuilder.Entity("BGC_DataAccess.Entities.RpgSessionGame", b =>
                {
                    b.HasOne("BGC_DataAccess.Entities.GameVersion", "GameVersion")
                        .WithMany("RpgSessionGames")
                        .HasForeignKey("GameVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BGC_DataAccess.Entities.RpgSession", "RpgSession")
                        .WithMany("RpgSessionGames")
                        .HasForeignKey("RpgSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameVersion");

                    b.Navigation("RpgSession");
                });

            modelBuilder.Entity("BGC_DataAccess.Entities.Game", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("BGC_DataAccess.Entities.GameSession", b =>
                {
                    b.Navigation("GameSessionRegistrations");

                    b.Navigation("GamesSessionGames");
                });

            modelBuilder.Entity("BGC_DataAccess.Entities.GameTable", b =>
                {
                    b.Navigation("GameSessions");

                    b.Navigation("RpgSessions");
                });

            modelBuilder.Entity("BGC_DataAccess.Entities.GameVersion", b =>
                {
                    b.Navigation("GameSessionGames");

                    b.Navigation("RpgSessionGames");
                });

            modelBuilder.Entity("BGC_DataAccess.Entities.Member", b =>
                {
                    b.Navigation("GameSessionRegistrations");

                    b.Navigation("GameSessions");

                    b.Navigation("RpgCampaignRegistrations");

                    b.Navigation("RpgCampaigns");
                });

            modelBuilder.Entity("BGC_DataAccess.Entities.RpgCampaign", b =>
                {
                    b.Navigation("RpgCampaignRegistrations");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("BGC_DataAccess.Entities.RpgSession", b =>
                {
                    b.Navigation("RpgSessionGames");
                });
#pragma warning restore 612, 618
        }
    }
}
